use custom_errors::err_response::JsonResult;

pub async fn get() -> JsonResult {
    todo!()
}
